name: "Cache"

on:
    push:
        branches:
            - "main"

jobs:
    build-cache:
        name: Build Cache
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"

            - name: "Setup NodeJS"
              uses: "actions/setup-node@v4"
              with:
                  node-version: "23.x"

            - name: "Cache Dependencies"
              uses: "actions/cache@v3"
              id: "cache"
              env:
                  cache-name: "cache-node-modules"
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            - if: steps.cache.outputs.cache-hit != 'true'
              name: Install Dependencies
              run: "npm ci"
